name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hey @${{ github.event.issue.user.login }}. Thank you for creating an issue! A developer will review your issue as soon as possible. 
          
          Please keep in mind, if you're issue doesn't provide enough context, information or relevance to Terabit Desktop, we may close your issue as unresolved.
        pr-message: |
          Hello! Welcome to Terabit Desktop. This appears to be your first pull request.
